language: node_js
node_js:
- '0.11'

before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# - 'chmod +x generateWrappedZ3.sh'
# - './generateWrappedZ3.sh'

script:
- 'npm test'

notifications:
  slack: hpi:AoZKX6B1m6JVBphnsGGOgweU
